-- generated by spring, create ddl copied here

create table account
(
    id                     bigint not null
        primary key,
    balance                double precision,
    is_active              boolean,
    name                   varchar(255),
    type                   varchar(255),
    user_id                bigint,
    is_overdraft_allowed   boolean,
    overdraft_amount_limit double precision,
    overdraft_fee_amount   double precision
);

create table transaction
(
    id         bigint not null
        primary key,
    amount     double precision,
    timestamp  timestamp(6) with time zone,
    type       varchar(255),
    account_id bigint not null
        constraint fkmej834uwoui8kadks8mftl58n
            references account
);

-- written manually

create table users(
                      username varchar(50) not null primary key,
                      password varchar(500) not null,
                      enabled boolean not null);

create table authorities (
                             username varchar(50) not null,
                             authority varchar(50) not null,
                             constraint fk_authorities_users foreign key(username) references users(username));

create unique index ix_auth_username on authorities (username,authority);


INSERT INTO `users` (`username`, `password`, `enabled`)
VALUES ('admin01', '$2a$12$lYKt1oTOuLwJaCS1FSIpu.KbvM4.PwBFZKANkLIm.U7F8gGmBoBmi', true);

INSERT INTO `users` (`username`, `password`, `enabled`)
VALUES ('user01', '$2a$12$bhB5dAmxgEI5tEwpb8o1i.0/QKp7XjN1KtqQBONSd/ksWmF8hEULi', true);


INSERT INTO `authorities` (`username`, `authority`)
VALUES ('admin01', 'ROLE_ADMIN');

INSERT INTO `authorities` (`username`, `authority`)
VALUES ('user01', 'ROLE_USER');